import type { HarnessConfiguration } from '../config/configuration.js'
import { isVisionCapableModel } from '../vision/model-catalog.js'
import { normalizeProviderBaseUrl, usesDeepSeekMessagesEndpoint } from './provider-endpoint.js'

export interface RuntimeOverlayOptions {
  readonly claudeHooksConfigPath?: string
  readonly codexHooksConfigPath?: string
  readonly steeringPluginUrl?: string
}

export function renderRuntimeOverlay(configuration: HarnessConfiguration, options: RuntimeOverlayOptions = {}): string {
  const nativeDeepSeek = configuration.provider === 'deepseek-official' && usesDeepSeekMessagesEndpoint(configuration.baseUrl)
  const maxTokens = Math.min(256_000, configuration.contextWindowTokens)
  const models = advertisedModels(configuration)
  const schedule = configuration.scheduleEnabled ? [
    '- insert:',
    '    - id: schedule',
    "      name: '@deepseek-ai/dsh-schedule'",
    '',
  ] : []
  const hooks = [
    ...(options.claudeHooksConfigPath === undefined ? [] : [
      '- insert:',
      '    - id: hooks-claude-code',
      "      name: '@deepseek-ai/dsh-hooks-claude-code'",
      '      config:',
      `        configPath: ${JSON.stringify(options.claudeHooksConfigPath)}`,
      '',
    ]),
    ...(options.codexHooksConfigPath === undefined ? [] : [
      '- insert:',
      '    - id: hooks-codex',
      "      name: '@deepseek-ai/dsh-hooks-codex'",
      '      config:',
      `        configPath: ${JSON.stringify(options.codexHooksConfigPath)}`,
      '',
    ]),
  ]
  const deepSeekRoute = nativeDeepSeek ? [
    '- id: llm-deepseek',
    '  config:',
    // Keep endpoint and credential configuration in the same generated
    // settings generation as the model catalog so shared runtimes do not
    // serve a stale endpoint after a VS Code window changes configuration.
    '    apiKeyEnv: "DEEPSEEK_API_KEY"',
    `    baseURL: ${JSON.stringify(normalizeProviderBaseUrl(configuration.baseUrl))}`,
    '    thinking: enabled',
    `    reasoningEffort: ${configuration.reasoningEffort === 'xhigh' ? 'max' : configuration.reasoningEffort}`,
    `    defaultContextWindow: ${configuration.contextWindowTokens}`,
    `    maxTokens: ${maxTokens}`,
    '    models:',
    ...models.flatMap(model => [
      `      - id: ${JSON.stringify(model.id)}`,
      `        name: ${JSON.stringify(model.name)}`,
      `        contextWindow: ${configuration.contextWindowTokens}`,
      ...(isVisionCapableModel(model.id) ? ['        inputModalities: [text, image]'] : []),
      ...(model.id === 'deepseek-flash' ? ['        systemPromptUpdate: in-history'] : []),
    ]),
    '',
  ] : []
  const overlay = [
    '# Generated by DeDge DeepSeek Harness for VS Code.',
    '# Manual changes are overwritten on runtime start.',
    '# This VS Code UI does not mount the upstream browser Office preview.',
    '- id: office-to-pdf',
    '  disabled: true',
    '- id: ui-sidebar-documentpreview',
    '  disabled: true',
    '',
    ...(options.steeringPluginUrl === undefined ? [] : [
      '- insert:',
      '    - id: dedge-steering-interrupt',
      `      name: ${JSON.stringify(options.steeringPluginUrl)}`,
      '',
    ]),
    ...hooks,
    ...schedule,
    ...deepSeekRoute,
    ...(nativeDeepSeek ? [] : ['- id: llm-deepseek', '  disabled: true', '', ...renderGenericProvider(configuration)]),
    '- id: agent-default-model',
    '  config:',
    `    provider: ${JSON.stringify(configuration.provider)}`,
    `    model: ${JSON.stringify(configuration.model)}`,
    ...(nativeDeepSeek ? [`    reasoningEffort: ${configuration.reasoningEffort === 'xhigh' ? 'max' : configuration.reasoningEffort}`]
      : configuration.provider === 'deepseek-official' ? [`    reasoningEffort: ${configuration.reasoningEffort === 'max' ? 'xhigh' : configuration.reasoningEffort}`] : []),
    '',
    '- id: agent-presets',
    '  config:',
    `    default: ${JSON.stringify(configuration.agentPreset)}`,
    '',
    '- id: compaction-basic',
    '  config:',
    ...(configuration.compactionProvider === undefined || configuration.compactionProvider === '' || configuration.compactionModel === undefined || configuration.compactionModel === ''
      ? []
      : [`    summarizationProvider: ${JSON.stringify(configuration.compactionProvider)}`, `    summarizationModel: ${JSON.stringify(configuration.compactionModel)}`]),
    '',
    '- id: permission',
    '  config:',
    '    presets:',
    '      read-only:',
    '        sandbox: read-only',
    '        approval: ask',
    '        name: Read only',
    '        description: Prevent model-driven file mutations.',
    '      workspace-write:',
    '        sandbox: workspace-write',
    '        approval: ask',
    '        name: Workspace write',
    '        description: Allow workspace and temporary-directory writes; on Windows, a denied external executable may require one-time sandbox approval.',
    '      danger-full-access:',
    '        sandbox: danger-full-access',
    '        approval: never',
    '        name: Full access',
    '        description: Allow unrestricted writes without approvals.',
    `    defaultPreset: ${configuration.permissionMode}`,
    '',
  ]
  return overlay.join('\n')
}

function renderGenericProvider(configuration: HarnessConfiguration): string[] {
  const provider = configuration.provider.trim()
  const api = /anthropic|claude/iu.test(provider) ? 'anthropic-messages' : 'openai-completions'
  const models = advertisedModels(configuration)
  const deepSeekCompat = provider === 'deepseek-official'
  return [
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
    `      ${JSON.stringify(provider)}:`,
    '        apiKeyEnv: DEEPSEEK_API_KEY',
    `        api: ${JSON.stringify(api)}`,
    `        baseURL: ${JSON.stringify(configuration.baseUrl)}`,
    ...(deepSeekCompat ? ['        compat:', '          thinkingFormat: deepseek'] : []),
    `        defaultContextWindow: ${configuration.contextWindowTokens}`,
    '        models:',
    ...models.flatMap(model => [
      `          - id: ${JSON.stringify(model.id)}`,
      `            name: ${JSON.stringify(model.name)}`,
      `            contextWindow: ${configuration.contextWindowTokens}`,
      ...(isVisionCapableModel(model.id) ? ['            input: [text, image]'] : []),
      ...(deepSeekCompat ? ['            reasoningEfforts:', '              off:', '              low: low', '              high: high', '              xhigh: max'] : []),
    ]),
    '',
  ]
}

function advertisedModels(configuration: HarnessConfiguration): Array<{ readonly id: string; readonly name: string }> {
  const defaults = configuration.provider === 'deepseek-official'
      ? [
        { id: 'deepseek-flash', name: 'DeepSeek-V41-Flash' },
        { id: 'deepseek-v4-flash', name: 'DeepSeek-V4-Flash' },
        { id: 'deepseek-v4-pro', name: 'DeepSeek-V4-Pro' },
        { id: 'deepseek-v4-flash-vision-exp', name: 'DeepSeek-V4-Flash-Vision-Exp' },
      ]
    : []
  if (!defaults.some(model => model.id === configuration.model)) {
    defaults.push({ id: configuration.model, name: configuration.model })
  }
  return defaults
}
