import type { HarnessConfiguration } from '../config/configuration.js'
import { isVisionCapableModel } from '../vision/model-catalog.js'

export function renderRuntimeOverlay(configuration: HarnessConfiguration): string {
  const thinking = configuration.reasoningEffort === 'off' ? 'disabled' : 'enabled'
  const maxTokens = Math.min(256_000, configuration.contextWindowTokens)
  const models = advertisedModels(configuration)
  const schedule = configuration.scheduleEnabled ? [
    '- insert:',
    '    - id: schedule',
    "      name: '@deepseek-ai/dsh-schedule'",
    '',
  ] : []
  const deepSeekRoute = configuration.provider === 'deepseek-official' ? [
    '- id: llm-deepseek',
    '  config:',
    // Keep the endpoint and credential reference in the same generated
    // settings generation as the model catalog. alpha.3 otherwise resolves
    // them from the process environment, which can leave a shared runtime
    // serving a stale endpoint after a VS Code window changes configuration.
    '    apiKeyEnv: "DEEPSEEK_API_KEY"',
    `    baseURL: ${JSON.stringify(normalizeProviderBaseUrl(configuration.baseUrl))}`,
    `    thinking: ${thinking}`,
    `    reasoningEffort: ${configuration.reasoningEffort}`,
    `    defaultContextWindow: ${configuration.contextWindowTokens}`,
    `    maxTokens: ${maxTokens}`,
    '    models:',
    ...models.flatMap(model => [
      `      - id: ${JSON.stringify(model.id)}`,
      `        name: ${JSON.stringify(model.name)}`,
      `        contextWindow: ${configuration.contextWindowTokens}`,
      ...(isVisionCapableModel(model.id) ? ['        inputModalities: [text, image]'] : []),
    ]),
    '',
  ] : []
  const overlay = [
    '# Generated by DeDge DeepSeek Harness for VS Code.',
    '# Manual changes are overwritten on runtime start.',
    ...schedule,
    ...deepSeekRoute,
    ...(configuration.provider === 'deepseek-official' ? [] : renderGenericProvider(configuration)),
    '- id: agent-default-model',
    '  config:',
    `    provider: ${JSON.stringify(configuration.provider)}`,
    `    model: ${JSON.stringify(configuration.model)}`,
    '',
    '- id: agent-presets',
    '  config:',
    `    default: ${JSON.stringify(configuration.agentPreset)}`,
    '',
    '- id: compaction-basic',
    '  config:',
    ...(configuration.compactionProvider === undefined || configuration.compactionProvider === '' || configuration.compactionModel === undefined || configuration.compactionModel === ''
      ? []
      : [`    summarizationProvider: ${JSON.stringify(configuration.compactionProvider)}`, `    summarizationModel: ${JSON.stringify(configuration.compactionModel)}`]),
    '',
    '- id: permission',
    '  config:',
    '    presets:',
    '      read-only:',
    '        sandbox: read-only',
    '        approval: ask',
    '        name: Read only',
    '        description: Prevent model-driven file mutations.',
    '      workspace-write:',
    '        sandbox: workspace-write',
    '        approval: ask',
    '        name: Workspace write',
    '        description: Allow workspace and temporary-directory writes; on Windows, a denied external executable may require one-time sandbox approval.',
    '      danger-full-access:',
    '        sandbox: danger-full-access',
    '        approval: never',
    '        name: Full access',
    '        description: Allow unrestricted writes without approvals.',
    `    defaultPreset: ${configuration.permissionMode}`,
    '',
  ]
  return overlay.join('\n')
}

/** alpha.3 appends `/chat/completions` directly to this value. */
function normalizeProviderBaseUrl(value: string): string {
  return value.replace(/\/+$/u, '')
}

function renderGenericProvider(configuration: HarnessConfiguration): string[] {
  const provider = configuration.provider.trim()
  const api = /anthropic|claude/iu.test(provider) ? 'anthropic-messages' : 'openai-completions'
  const model = configuration.model.trim()
  return [
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
    `      ${JSON.stringify(provider)}:`,
    '        apiKeyEnv: DEEPSEEK_API_KEY',
    `        api: ${JSON.stringify(api)}`,
    `        baseURL: ${JSON.stringify(configuration.baseUrl)}`,
    `        defaultContextWindow: ${configuration.contextWindowTokens}`,
    '        models:',
    `          - id: ${JSON.stringify(model)}`,
    `            name: ${JSON.stringify(model)}`,
    `            contextWindow: ${configuration.contextWindowTokens}`,
    ...(isVisionCapableModel(model) ? ['            input: [text, image]'] : []),
    '',
  ]
}

function advertisedModels(configuration: HarnessConfiguration): Array<{ readonly id: string; readonly name: string }> {
  const defaults = configuration.provider === 'deepseek-official'
    ? [
        { id: 'deepseek-v4-flash', name: 'DeepSeek-V4-Flash' },
        { id: 'deepseek-v4-pro', name: 'DeepSeek-V4-Pro' },
        { id: 'deepseek-v4-flash-vision-exp', name: 'DeepSeek-V4-Flash-Vision-Exp' },
      ]
    : []
  if (!defaults.some(model => model.id === configuration.model)) {
    defaults.push({ id: configuration.model, name: configuration.model })
  }
  return defaults
}
